language: node_js
node_js: 10

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

stages:
  - 'Test'
  - name: 'Deploy'
    if: branch = master AND type = push

jobs:
  fail_fast: true
  include:
    - stage: 'Test'
      name: 'Conventional Commits'
      script: commitlint-travis
    - name: 'Lint'
      script: yarn lint
    - name: 'Floating Dependencies'
      install:
        - yarn install --no-lockfile --non-interactive
    - name: 'Fixed Dependencies'
	  before_script: yarn build && yarn global add codecov
	  script:
		- node_modules/.bin/nyc yarn test
      after_success: codecov
    - stage: 'Deploy'
      name: 'Publish to npm'
      script: yarn semantic-release

install:
  - yarn install --non-interactive


