language: node_js
node_js: stable
yarn: true

before_script: yarn global add codecov
script:
  - node_modules/.bin/nyc yarn test && yarn travis-deploy-once "yarn semantic-release"
after_success: codecov